// Harvests the real brand webfonts out of a Next.js build into the library.
//
// next/font downloads Sora / Inter / Noto Sans Thai / IBM Plex Sans Thai at
// build time and rewrites them under hashed family names (`__Sora_1a977f`).
// The design system has to ship those same files under their real names, or
// anything built from the library renders in a fallback face.
//
// Run `npm run build` at the repo root first, then `node scripts/extract-fonts.mjs`.

import { readFileSync, writeFileSync, readdirSync, mkdirSync, copyFileSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, basename } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = join(here, "..");
const repoRoot = join(pkgRoot, "..", "..");
const cssDir = join(repoRoot, ".next", "static", "css");
const mediaDir = join(repoRoot, ".next", "static", "media");
const outDir = join(pkgRoot, "fonts");

let cssFiles;
try {
  cssFiles = readdirSync(cssDir).filter((f) => f.endsWith(".css"));
} catch {
  console.error(`no Next build found at ${cssDir} — run "npm run build" at the repo root first`);
  process.exit(1);
}

const source = cssFiles.map((f) => readFileSync(join(cssDir, f), "utf8")).join("\n");
const rules = source.match(/@font-face\{[^}]*\}/g) ?? [];

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const copied = new Set();
const families = new Map();
const out = [];

for (const rule of rules) {
  const family = rule.match(/font-family:([^;]+);/)?.[1]?.replace(/["']/g, "").trim();
  if (!family || !family.startsWith("__")) continue;
  // `__Sora_1a977f` -> `Sora`; `__IBM_Plex_Sans_Thai_ab12cd` -> `IBM Plex Sans Thai`.
  // Fallback faces are local() metric-adjust shims — they carry no file.
  if (family.includes("_Fallback_")) continue;
  const real = family.replace(/^__/, "").replace(/_[0-9a-f]{6}$/, "").replace(/_/g, " ");

  const file = rule.match(/url\(([^)]+)\)/)?.[1];
  if (!file) continue;
  const name = basename(file);
  if (!copied.has(name)) {
    copyFileSync(join(mediaDir, name), join(outDir, name));
    copied.add(name);
  }

  families.set(real, (families.get(real) ?? 0) + 1);
  out.push(
    rule
      .replace(/font-family:[^;]+;/, `font-family:"${real}";`)
      .replace(/url\([^)]+\)/, `url("./${name}")`),
  );
}

writeFileSync(
  join(outDir, "fonts.css"),
  `/* Generated by scripts/extract-fonts.mjs — do not edit by hand.\n` +
    `   Brand webfaces harvested from the Next.js build, renamed from\n` +
    `   next/font's hashed families back to their real names. */\n` +
    out.join("\n") +
    "\n",
);

console.log(`fonts: ${copied.size} woff2 + fonts.css written to ${outDir}`);
for (const [family, n] of families) console.log(`  ${family} — ${n} face(s)`);
